# Generated by Django 3.1.3 on 2023-05-01 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0013_auto_20230427_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pcategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pcategory',
            name='meta_title',
        ),
    ]
