# Generated by Django 3.1.3 on 2023-05-01 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0015_carbrand_carmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carmodel',
        ),
    ]
