# Generated by Django 3.1.3 on 2023-05-01 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0017_carmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carbrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_service.carbrand'),
        ),
        migrations.AddField(
            model_name='product',
            name='carmodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home_service.carmodel'),
        ),
    ]
